added lists, snackbar &  other minor changes
irajbhinde/Endless-Component-Library pull request #4
Opened 2022-02-08 09:38 UTC by irajbhinde

Hey! Please review my code & let me know if any changes could be made. 

**Kindly ignore the changes made in components other than list & snack**

Added Components -

**Lists**

1. Simple Lists
2. Spaced Lists
3. Stacked Lists

**Snackbar**

1. Baseline Snackbar
2. Leading Snackbar

**GIFY** -

![list_snackbar](https://user-images.githubusercontent.com/68704186/152942720-a425b991-982a-473e-97dc-d6c36104e227.gif)

2022-02-09 06:32 UTC, ark2002 requested changes
these changes rest looks fine

2022-02-09 06:32 UTC, ark2002 commented on Components/List/lists.css
> +  font-size: 20px;
better to use relative units here

2022-02-09 06:32 UTC, ark2002 commented on Components/List/lists.css
> +}
here aswell above 10px u can use relative units

2022-02-09 06:32 UTC, ark2002 commented on Components/Snackbar/snackbar.css
> +    border-radius: 4px;
its better using one color codes dont mic up hex and rgb

2022-02-10 18:55 UTC, SRUJANA-PENUGONDA13 commented on Components/Snackbar/snackbar.html
> +<!DOCTYPE html>
Remove unnecessary blank lines and spaces in document

2022-02-10 19:05 UTC, SRUJANA-PENUGONDA13 commented on Components/List/lists.html
> +                                &lt;ul class="spaced-list"&
You have mentioned spaced-list class in code snippet but you haven't used anywhere in lists page. You didn't provided example for spaced list.
I think you can add spaced list class to current simple list example which covers both the lists Otherwise add one more list example for spaced list.

2022-02-10 19:06 UTC, SRUJANA-PENUGONDA13 commented
Everything looks good. Suggested few things. once look into it. Try to remove unnecessary blank spaces and lines in all files of your application

2022-02-11 04:48 UTC, merged